/**
 * Agent Reporter
 * Generates structured remediation reports for AI agents (JSON + Markdown)
 */

import type { ScanResult, Finding, Severity } from '../types.js';

const SEV_ORDER: Record<Severity, number> = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };

function sortedFindings(findings: Finding[]): Finding[] {
  return [...findings].sort((a, b) => {
    const sd = SEV_ORDER[a.severity] - SEV_ORDER[b.severity];
    if (sd !== 0) return sd;
    return a.location.file.localeCompare(b.location.file);
  });
}

export function formatAgentJson(result: ScanResult, version: string): string {
  const sorted = sortedFindings(result.findings);

  const tasks = sorted.map((f, i) => ({
    id: `task-${i + 1}`,
    priority: f.severity,
    rule_id: f.ruleId,
    rule_name: f.ruleName,
    category: f.category,
    file: f.location.file,
    line: f.location.startLine,
    snippet: f.location.snippet || null,
    description: f.message,
    remediation: f.remediation || f.message,
    references: {
      owasp: (f.metadata?.owasp as string) || null,
      cwe: (f.metadata?.cwe as string) || null,
    },
  }));

  const report = {
    preflight_version: version,
    generated: result.timestamp,
    scan_root: result.scanRoot,
    score: result.score,
    total_findings: result.findings.length,
    summary: result.summary,
    tasks,
  };

  return JSON.stringify(report, null, 2);
}

export function formatAgentMarkdown(result: ScanResult, version: string): string {
  const lines: string[] = [];

  lines.push('# Preflight Security Report');
  lines.push('');
  lines.push(`**Score:** ${result.score}/100 | **Findings:** ${result.findings.length} | **Files:** ${result.filesScanned}`);
  lines.push('');

  if (result.findings.length === 0) {
    lines.push('No security findings detected.');
    return lines.join('\n');
  }

  // Group by severity
  const grouped = new Map<Severity, Finding[]>();
  for (const f of result.findings) {
    const list = grouped.get(f.severity) ?? [];
    list.push(f);
    grouped.set(f.severity, list);
  }

  const sevOrder: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

  for (const sev of sevOrder) {
    const findings = grouped.get(sev);
    if (!findings || findings.length === 0) continue;

    lines.push(`## ${sev.charAt(0).toUpperCase() + sev.slice(1)} (${findings.length})`);
    lines.push('');

    for (const f of findings) {
      lines.push(`### ${f.ruleId}: ${f.ruleName}`);
      lines.push(`- **File:** \`${f.location.file}:${f.location.startLine}\``);
      lines.push(`- **Category:** ${f.category}`);

      if (f.location.snippet) {
        lines.push('- **Snippet:**');
        lines.push('  ```');
        for (const line of f.location.snippet.split('\n')) {
          lines.push(`  ${line}`);
        }
        lines.push('  ```');
      }

      const fix = f.remediation || f.message;
      lines.push(`- **Fix:** ${fix}`);

      if (f.metadata?.owasp || f.metadata?.cwe) {
        const refs: string[] = [];
        if (f.metadata.owasp) refs.push(f.metadata.owasp as string);
        if (f.metadata.cwe) refs.push(f.metadata.cwe as string);
        lines.push(`- **References:** ${refs.join(', ')}`);
      }

      lines.push('');
    }
  }

  // Summary table
  lines.push('## Summary');
  lines.push('');
  lines.push('| Severity | Count |');
  lines.push('|----------|-------|');
  for (const sev of sevOrder) {
    const count = result.summary[sev];
    if (count > 0) {
      lines.push(`| ${sev.charAt(0).toUpperCase() + sev.slice(1)} | ${count} |`);
    }
  }
  lines.push('');
  lines.push(`*Generated by Preflight v${version}*`);
  lines.push('');

  return lines.join('\n');
}
